apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamimage
  namespace: hackaton
  labels:
    app: k8s-hackaton
spec:
  replicas: 10
  selector:
    matchLabels:
      app: k8s-hackaton
  template:
    metadata:
      labels:
        app: k8s-hackaton
    spec:
      containers:
      - name: k8s-hackaton
        image: europe-north1-docker.pkg.dev/gke-hackaton-426920/gke-hackaton/streamimage:latest
