apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-active
  namespace: bluegreen
spec:
  selector:
    app: rollout-bluegreen
  ports:
    - port: 80
      targetPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
  namespace: bluegreen
spec:
  selector:
    app: rollout-bluegreen
  ports:
    - port: 80
      targetPort: 8080
